# ---------------------------------------------------------------------------------------------
# This docker compose file bring up the Docker containers for run Hyperledger Fabric Network
# ---------------------------------------------------------------------------------------------
version: '2'

networks:
  network:

services:

  ca.residents.jeabc.com:
    container_name: ca.residents.jeabc.com
    image: hyperledger/fabric-ca:1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-residents
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.residents.jeabc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/93c5f3d18848a01fa79f5377a572ad3217d8813b5df199a61196906aa4efb892_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.residents.jeabc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/93c5f3d18848a01fa79f5377a572ad3217d8813b5df199a61196906aa4efb892_sk
      #- FABRIC_CA_SERVER_DB_TYPE=mysql
      #- FABRIC_CA_SERVER_DB_DATASOURCE=root:${MYSQL_PASSWORD}@tcp(mysql.ca.govt:3306)/fabric_ca?parseTime=true
    ports:
      - "15111:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.residents.jeabc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/93c5f3d18848a01fa79f5377a572ad3217d8813b5df199a61196906aa4efb892_sk'
    volumes:
      - ./channel/crypto-config/peerOrganizations/residents.jeabc.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./Backup/ca-residents:/etc/hyperledger/fabric-ca-server
    networks:
      - network


  ca.bank.jeabc.com:
    container_name: ca.bank.jeabc.com
    image: hyperledger/fabric-ca:1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bank
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bank.jeabc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/bb8bfb4a197bbb6453d276a0f6ac7ced4d2f7db566325636f624ebd68a8938fe_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bank.jeabc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/bb8bfb4a197bbb6453d276a0f6ac7ced4d2f7db566325636f624ebd68a8938fe_sk
      #- FABRIC_CA_SERVER_DB_TYPE=mysql
      #- FABRIC_CA_SERVER_DB_DATASOURCE=root:${MYSQL_PASSWORD}@tcp(mysql.ca.builder:3306)/fabric_ca?parseTime=true
    ports:
      - "15112:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bank.jeabc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/bb8bfb4a197bbb6453d276a0f6ac7ced4d2f7db566325636f624ebd68a8938fe_sk'
    volumes:
      - ./channel/crypto-config/peerOrganizations/bank.jeabc.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./Backup/ca-bank:/etc/hyperledger/fabric-ca-server
    networks:
      - network


  ca.utilitycompany.jeabc.com:
    container_name: ca.utilitycompany.jeabc.com
    image: hyperledger/fabric-ca:1.1.0
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-utilitycompany
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.utilitycompany.jeabc.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/3ca56020211f12683094ae57a8bcfd6edb33ffee67c72c351bd35cc0801bc82d_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.utilitycompany.jeabc.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/3ca56020211f12683094ae57a8bcfd6edb33ffee67c72c351bd35cc0801bc82d_sk
      #- FABRIC_CA_SERVER_DB_TYPE=mysql
      #- FABRIC_CA_SERVER_DB_DATASOURCE=root:${MYSQL_PASSWORD}@tcp(mysql.ca.user:3306)/fabric_ca?parseTime=true
    ports:
      - "15113:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.utilitycompany.jeabc.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/3ca56020211f12683094ae57a8bcfd6edb33ffee67c72c351bd35cc0801bc82d_sk'
    volumes:
      - ./channel/crypto-config/peerOrganizations/utilitycompany.jeabc.com/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./Backup/ca-utilitycompany:/etc/hyperledger/fabric-ca-server
    networks:
      - network


  zookeeper0:
    container_name: zookeeper0.jeabc.com
    extends:
      file: base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    volumes:
      - ./Backup/Zookeeper/zk0/data:/data
      - ./Backup/Zookeeper/zk0/datalog:/datalog
    networks:
      - network

  zookeeper1:
    container_name: zookeeper1.jeabc.com
    extends:
      file: base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    volumes:
      - ./Backup/Zookeeper/zk1/data:/data
      - ./Backup/Zookeeper/zk1/datalog:/datalog
    networks:
      - network

  zookeeper2:
    container_name: zookeeper2.jeabc.com
    extends:
      file: base.yaml
      service: zookeeper-base
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    volumes:
      - ./Backup/Zookeeper/zk2/data:/data
      - ./Backup/Zookeeper/zk2/datalog:/datalog
    networks:
      - network

  kafka0:
    container_name: kafka0.jeabc.com
    extends:
      file: base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    volumes:
      - ./Backup/Kafka/kafka0:/tmp/kafka-logs
    networks:
      - network
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka1:
    container_name: kafka1.jeabc.com
    extends:
      file: base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    volumes:
      - ./Backup/Kafka/kafka1:/tmp/kafka-logs
    networks:
      - network
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka2:
    container_name: kafka2.jeabc.com
    extends:
      file: base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    volumes:
      - ./Backup/Kafka/kafka2:/tmp/kafka-logs
    networks:
      - network
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka3:
    container_name: kafka3.jeabc.com
    extends:
      file: base.yaml
      service: kafka-base
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    volumes:
      - ./Backup/Kafka/kafka3:/tmp/kafka-logs
    networks:
      - network
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  orderer1.jeabc.com:
    container_name: orderer1.jeabc.com
    extends:
      file: base.yaml
      service: orderer-base
    ports:
      - 15101:7050
    volumes:
      - ./channel/crypto-config/ordererOrganizations/jeabc.com/orderers/orderer1.jeabc.com/:/etc/hyperledger/msp/orderer
    networks:
      - network
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  orderer2.jeabc.com:
    container_name: orderer2.jeabc.com
    extends:
      file: base.yaml
      service: orderer-base
    ports:
      - 15102:7050
    volumes:
      - ./channel/crypto-config/ordererOrganizations/jeabc.com/orderers/orderer2.jeabc.com/:/etc/hyperledger/msp/orderer
    networks:
      - network
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  orderer3.jeabc.com:
    container_name: orderer3.jeabc.com
    extends:
      file: base.yaml
      service: orderer-base
    ports:
      - 15103:7050
    volumes:
      - ./channel/crypto-config/ordererOrganizations/jeabc.com/orderers/orderer3.jeabc.com/:/etc/hyperledger/msp/orderer
    networks:
      - network
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  couchdb.peer0.residents.jeabc.com:
    container_name: couchdb.peer0.residents.jeabc.com
    extends:
      file: base.yaml
      service: couch-base
    volumes:
      - ./Backup/Residents/CouchDb/peer0:/opt/couchdb/data
    networks:
      - network

  peer0.residents.jeabc.com:
    container_name: peer0.residents.jeabc.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.residents.jeabc.com
      - CORE_PEER_LOCALMSPID=ResidentsMSP
      - CORE_PEER_ADDRESS=peer0.residents.jeabc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.residents.jeabc.com:7051
      - CORE_PEER_LISTENADDRESS=peer0.residents.jeabc.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.residents.jeabc.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.residents.jeabc.com:5984
    ports:
      - 15121:7051
      - 15123:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel/crypto-config/peerOrganizations/residents.jeabc.com/peers/peer0.residents.jeabc.com/:/etc/hyperledger/msp/peer
      - ./Backup/Residents/Peer/peer0:/var/hyperledger/production
    depends_on:
      - orderer1.jeabc.com
      - orderer2.jeabc.com
      - orderer3.jeabc.com
      - couchdb.peer0.residents.jeabc.com
    networks:
      - network

  couchdb.peer0.bank.jeabc.com:
    container_name: couchdb.peer0.bank.jeabc.com
    extends:
      file: base.yaml
      service: couch-base
    volumes:
      - ./Backup/Bank/CouchDb/peer0:/opt/couchdb/data
    networks:
      - network

  peer0.bank.jeabc.com:
    container_name: peer0.bank.jeabc.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bank.jeabc.com
      - CORE_PEER_LOCALMSPID=BankMSP
      - CORE_PEER_ADDRESS=peer0.bank.jeabc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank.jeabc.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.bank.jeabc.com:5984
      - CORE_PEER_LISTENADDRESS=peer0.bank.jeabc.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.bank.jeabc.com:7051
    ports:
      - 15133:7051
      - 15135:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel/crypto-config/peerOrganizations/bank.jeabc.com/peers/peer0.bank.jeabc.com/:/etc/hyperledger/msp/peer
      - ./Backup/Bank/Peer/peer0:/var/hyperledger/production
    depends_on:
      - orderer1.jeabc.com
      - orderer2.jeabc.com
      - orderer3.jeabc.com
      - couchdb.peer0.bank.jeabc.com
    networks:
      - network

  couchdb.peer0.utilitycompany.jeabc.com:
    container_name: couchdb.peer0.utilitycompany.jeabc.com
    extends:
      file: base.yaml
      service: couch-base
    volumes:
      - ./Backup/UtilityCompany/CouchDb/peer0:/opt/couchdb/data
    networks:
      - network

  peer0.utilitycompany.jeabc.com:
    container_name: peer0.utilitycompany.jeabc.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.utilitycompany.jeabc.com
      - CORE_PEER_LOCALMSPID=UtilityCompanyMSP
      - CORE_PEER_ADDRESS=peer0.utilitycompany.jeabc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.utilitycompany.jeabc.com:7051
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.utilitycompany.jeabc.com:5984
      - CORE_PEER_LISTENADDRESS=peer0.utilitycompany.jeabc.com:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer0.utilitycompany.jeabc.com:7051
    ports:
      - 15145:7051
      - 15147:7053
    volumes:
      - /var/run/:/host/var/run/
      - ./channel/crypto-config/peerOrganizations/utilitycompany.jeabc.com/peers/peer0.utilitycompany.jeabc.com/:/etc/hyperledger/msp/peer
      - ./Backup/UtilityCompany/Peer/peer0:/var/hyperledger/production
    depends_on:
      - orderer1.jeabc.com
      - orderer2.jeabc.com
      - orderer3.jeabc.com
      - couchdb.peer0.utilitycompany.jeabc.com
    networks:
      - network
